use_frameworks!

platform :ios, '9.0'

target 'lvcode_Example' do
  pod 'lvcode', :path => '../'

  target 'lvcode_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
